[package]
name = "letui-ffi"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
taffy = "0.9.1"

[lib]
name = "letui_ffi"
crate-type = ["cdylib"]
